name: Telegram Notifications
on:
  push:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, reopened, locked, unlocked]
  issue_comment:
    types: [created, deleted]
  pull_request:
    types: [opened, reopened, closed, locked, unlocked]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Telegram Notifications for Actions on GitHub
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '6281738606:AAEmotwRDbHVkTvzwOeNsAsdqN0g9D2zbLU'
          chat_id: '-1001719051389'
